### ISSUE TITLE
Don't know the title?

### ISSUE THREAD

**Issue by Sickle2** [co-cart/co-cart#463]
Why Items Are Moved from remove_items to items When Re-fetching the Cart After Deleting an Item

http://xxxx.com/wordpress/wp-json/cocart/v2/cart/item/4a02b4e88bea58e3d599e6c558832206
<img width="734" alt="image" src="https://github.com/user-attachments/assets/9f4d2b7f-8c83-4e86-b879-9de012bdcb71">

http://xxxx.com/wordpress/wp-json/cocart/v2/cart
<img width="578" alt="image" src="https://github.com/user-attachments/assets/50cd1a28-cb12-4f69-b4c0-850db743b533">
<img width="586" alt="image" src="https://github.com/user-attachments/assets/06737733-29c7-486f-8703-043d69268734">

**Comment by Sickle2** [comment]
cocart version ： 4.3.10

**Comment by seb86** [comment]
Conditions?

**Comment by Sickle2** [comment]
After deleting a product from the shopping cart using the API and obtaining information using the get API, the item was not deleted

**Comment by seb86** [comment]
I already see that. What I meant was, guest cart or authenticated customer and what type of authentication method used?

**Comment by Sickle2** [comment]
JWT and already logged in .used [JWT Authentication for WP-API](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) plugin.

**Comment by seb86** [comment]
@Sickle2  Can you verify if this happens with previous versions of CoCart or JWT?

**Comment by Sickle2** [comment]
Cocart ： 4.3.8 ， JWT：1.3.4 。 I tried upgrading Cockart to the latest version, but it didn't solve the problem。My WooCommerce version is 9.3.3, does it need to be upgraded

**Comment by seb86** [comment]
Do other cart endpoints work with JWT?

**Comment by Sickle2** [comment]
Currently, only deleting items is problematic

**Comment by Sickle2** [comment]
I have found the problem. I used TOTAL CACHE and after disabling it, COCart worked normally. Can this be solved

**Comment by widdydev** [comment]
This is probably related to my [issue](https://github.com/co-cart/co-cart/issues/461).
Yet I'm not fully convinced, that this is a caching issue.

**Comment by seb86** [comment]
> I have found the problem. I used TOTAL CACHE and after disabling it, CoCart worked normally. Can this be solved

If it is related to Total Cache. There is a section on [this article](https://www.boldgrid.com/support/w3-total-cache/rest-api/) explaining how to exclude REST API endpoints from being cached.

I have not yet found a filter to program this so it works out the box but a little FYI on cache plugins. They are not designed for REST API's in mind. They use the same rules as page caching because it relies on calculating the last modified date of a post/page.

Custom API's like CoCart's cart API do not have a last modified date as they don't rely on post data.

So you will have to configure your cache plugin accordingly.

**Comment by widdydev** [comment]
I'm wondering what's the difference between these two paths when this is a caching issue?:
1. Get Cart -> Add item to cart -> Update cart item (Set different quantity) -> Get cart => The last get cart shows the expected state
2. Get Cart -> Add item to cart -> Remove item from cart -> get Cart => Invalid state

I also tried this on a freshly installed wordpress instance without additional caching plugins enabled. Still not working as expected.

**Comment by seb86** [comment]
I honestly don't know. It's possible it's due to being a DELETE request method. I don't have a copy of the Pro cache plugin to see what they are doing but I am currently looking into improving the cache mechanics in CoCart so it's better detected.

**Comment by seb86** [comment]
Version 4.3.11 just released to help with cache related issues. Let me know if that helped your situation please.

**Comment by Sickle2** [comment]
At present, it seems that this problem has been solved

**Comment by sufiyan05** [comment]
we are using Version 4.3.13 and still we are facing this issue in production server our app is not functioning due to this issue.
we are still getting removed item, do we need to use the specific Version 4.3.11

**Comment by widdydev** [comment]
> we are using Version 4.3.13 and still we are facing this issue in production server our app is not functioning due to this issue. we are still getting removed item, do we need to use the specific Version 4.3.11

Same here

**Comment by seb86** [comment]
I understand your concern and I appreciate your patience while I try to solve this problem.

**Comment by sufiyan05** [comment]
Your plugin is truly remarkable and has been a game-changer for many projects! It would be even more fantastic if the functionality remains consistent across updates.
Keep up the great work! 🌟

**Comment by seb86** [comment]
Closing this issue as it is related to #461  Continue the conversation there please.
